### ISSUE TITLE
Name Attribute is optional but required inside the wrapper

### ISSUE THREAD

**Issue by jaschaio** [robertstaddon/GetResponse-PHP-Wrapper#11]
If you try to add a contact without a $name gets you an "Invalid params" error from GetResponse.

Currently the wrapper uses the $name variable even if its not defined or empty.

See line 462:
`$params = array('campaign' => $campaign, 'action' => $action, 'name' => $name, 'email' => $email, 'cycle_day' => $cycle_day);`

I changed it into
```
if (!empty($name)) {
    $params = array('campaign' => $campaign, 'action' => $action, 'name' => $name, 'email' => $email, 'cycle_day' => $cycle_day);
} else {
    $params = array('campaign' => $campaign, 'action' => $action, 'email' => $email, 'cycle_day' => $cycle_day);
}
```

Now the parameter is optional and you won't get an error from GetResponse if you don't define it or when its empty when calling the function.

**Comment by robertstaddon** [comment]
Good point, jaschaio.

Here's perhaps a little cleaner way to do it:

    $params = array('campaign' => $campaign, 'action' => $action, 'email' => $email, 'cycle_day' => $cycle_day);
    	
    if(!empty($name))
        $params['name'] = $name;

Would this work for you?

**Comment by jaschaio** [comment]
Looks great, thanks for the response

**Comment by robertstaddon** [comment]
Ok! I've updated the wrapper.
