### ISSUE TITLE
Warning in ping method when execute returns null/etc

### ISSUE THREAD

**Issue by strangerstudios** [robertstaddon/GetResponse-PHP-Wrapper#12]
I was getting notices because on this line $response->ping was sometimes not set here:

https://github.com/robertstaddon/GetResponse-PHP-Wrapper/blob/master/PHPwrapper/GetResponseAPI.class.php#L69

For example, if an invalid API key was used $response was NULL here.

I added code like this:

    if(!empty($response) && !empty($response->ping))
        return $response->ping;
    else
        return $response;

**Comment by robertstaddon** [comment]
Good point! I've just updated the class with your code.
