### ISSUE TITLE
addContact() returns NULL

### ISSUE THREAD

**Issue by VanTudor** [robertstaddon/GetResponse-PHP-Wrapper#7]
when i do

    $response = $api->addContact($_GET['campaign_id'], 'some name', $_GET['email']);

    var_dump($response); 
prints "NULL"

I can confirm the variables in the $_GET array are correct.

**Comment by VanTudor** [comment]
I dugged into the wrapper's code and i found out that the errors don't get printed, which explains why the returned value didn't match the expected ones, as stated on the getresponse APIwebsite. 

What happened in my case, was that $_SERVER['REMOTE_ADDR'] - the method you use to get the ip - returned ":", which getresponse's API sees as an invalid parameter. This probably happened because i use xampp. Anyways, i'm working on a push right now. It should improve the usability.

**Comment by VanTudor** [comment]
You can close this. You merged my solution.

**Comment by jaschaio** [comment]
Hey @VanTudor, I still have the same problem. `addContact` returns `NULL`.

I have seen that in the wrappers code the IP is still defined by `$_SERVER['REMOTE_ADDR']`. I am not using xampp but MAMP (on Mac). My IPv6 is `::1` (equivalent for 127.0.0.1). I have seen somewhere that GetResponse rejects IPv6, but even if I change the wrapper code in Line 467 from `'ip' => $_SERVER['REMOTE_ADDR']` to something like `'ip' => '127.0.0.1'` its still not working.

What was your solution?

**Comment by jaschaio** [comment]
Sorry @VanTudor, I still had the old wrapper. I updated it and now it seems to work. Thanks a lot anyway

**Comment by VanTudor** [comment]
No problem. Glad it works. Come back to me if you encounter any problems.
